FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

# Install necessary dependencies
RUN pip install --no-cache-dir streamlit duckdb pandas

COPY dashboard/ /app/dashboard/

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/app.py"]
